references:
  wh40k_narrator:
    wav: refs/samples/Sergey_Chonishvili.wav
    x_vector_only: true
    description: Нарратор — Сергей Чонишвили
    characters:
    - narrator
    - system
    - loading_screen
    - Narrator
  kunrad:
    wav: refs/samples/Vsevolod_Kuznetsov.wav
    x_vector_only: true
    description: Кунрад — Всеволод Кузнецов
    characters:
    - Kunrad Voigtvir
    - Kunrad
  teodora:
    wav: refs/samples/Natalya_Kaznacheeva.wav
    x_vector_only: true
    description: Теодора — Наталья Казначеева
    characters:
    - Theodora
    - Theodora von Valancius
  abelard:
    wav: refs/samples/Mikhail_Pshenichny.wav
    x_vector_only: true
    description: Абеляр — Михаил Пшеничный
    characters:
    - Abelard Werserian
    - Abelard
  heinrix:
    wav: refs/samples/Nikita_Prozorovsky.wav
    x_vector_only: true
    description: Хайнрикс — Никита Прозоровский
    characters:
    - Heinrix van Calox
    - Heinrix
  pasqal:
    wav: refs/samples/Aleksandr_Klyukvin.wav
    x_vector_only: true
    description: Паскаль — Александр Клюквин
    characters:
    - Pasqal Haneumann
    - Pasqal
  solomon:
    wav: refs/samples/Oleg_Kutsenko.wav
    x_vector_only: true
    description: Соломон — Олег Куценко
    characters:
    - Solomon Antar
    - Solomon
  ulfar:
    wav: refs/samples/Aleksey_Myasnikov.wav
    x_vector_only: true
    description: Ульфар — Алексей Мясников
    characters:
    - Ulfar
  marazhai:
    wav: refs/samples/Sergey_Chikhachyov.wav
    x_vector_only: true
    description: Маражай — Сергей Чихачёв
    characters:
    - Marazhai Aezyrraesh
    - Marazhai
  edelthrad:
    wav: refs/samples/Ivan_Litvinov.wav
    x_vector_only: true
    description: Edelthrad — Иван Литвинов
    characters:
    - Edelthrad
  eogann:
    wav: refs/samples/Andrey_Kravets.wav
    x_vector_only: true
    description: Eogann — Андрей Кравец
    characters:
    - Eogann
  manipulus:
    wav: refs/samples/Vladimir_Antonik.wav
    x_vector_only: true
    description: Manipulus — Владимир Антоник
    characters:
    - Manipulus
  argenta:
    wav: refs/samples/Elena_Solovyova.wav
    x_vector_only: true
    description: Арджента — Елена Соловьёва
    characters:
    - Sister Argenta
    - Argenta
  idira:
    wav: refs/samples/Aglaya_Shilovskaya.wav
    x_vector_only: true
    description: Идира — Аглая Шиловская
    characters:
    - Idira Tlass
    - Idira
  cassia:
    wav: refs/samples/Anastasiya_Lapina.wav
    x_vector_only: true
    description: Кассия — Анастасия Лапина
    characters:
    - Cassia Orsellio
    - Cassia
  jae:
    wav: refs/samples/Irina_Kireeva.wav
    x_vector_only: true
    description: Джаэ — Ирина Киреева
    characters:
    - Jae Heydari
    - Jae
  kibellah:
    wav: refs/samples/Olga_Golovanova.wav
    x_vector_only: true
    description: Kibellah — Ольга Голованова
    characters:
    - Kibellah
  yrliet:
    wav: refs/samples/Lina_Ivanova.wav
    x_vector_only: true
    description: Йрлиет — Лина Иванова
    characters:
    - Yrliet Lanaeviss
    - Yrliet
  trazyn:
    wav: refs/samples/Vadim_Medvedev.wav
    x_vector_only: true
    description: Trazyn — Вадим Медведев
    characters:
    - Trazyn
  default_male:
    wav: refs/samples/Denis_Nekrasov.wav
    x_vector_only: true
    description: NPC (муж.) — Денис Некрасов
    characters:
    - Generic Male NPC
    - Default NPC
    - Smuggler
    - Psyker (NPC)
    - Psyker NPC
    - Psyker
    - Arbites (NPC)
    - Arbites NPC
    - Seneschal (NPC)
    - Seneschal NPC
    - Interrogator (NPC)
    - Interrogator NPC
  default_female:
    wav: refs/samples/Elena_Chebaturkina.wav
    x_vector_only: true
    description: NPC (жен.) — Елена Чебатуркина
    characters:
    - default_female
    - Generic Female NPC
    - NPC Female
    - female npc
