name: Environment Descriptions
description: Тексты описаний окружения (локации, предметы, интерьер) — не диалоговые реплики
total_phrases: 2
phrases:
- guid: 7a4156e5-b698-4ed2-aa6f-83c63197a062
  text: Массивный стол для переговоров, явно сработанный из настоящей древесины — невероятной ценности на борту пустотного корабля.
  parts:
  - speaker: narrator
    text_clean: Массивный стол для переговоров, явно сработанный из настоящей древесины — невероятной ценности на борту пустотного корабля.
- guid: f6c6482f-4b30-4b8a-9fda-bf831e038861
  text: Освещенный свечами алтарь с копией две тысяча триста сорок восьмого тома Лекс Империалис — свода священных законов Империума.
  parts:
  - speaker: narrator
    text_clean: Освещенный свечами алтарь с копией две тысяча триста сорок восьмого тома Лекс Империалис — свода священных законов Империума.
