#!/usr/bin/env python3
"""Extract GUID->role mapping from blueprints-pack.bbp to catalog/dialog_roles.yaml.

Role: answer (player option) | cue (NPC line) | unknown (not in dialog trees).

Usage:
    python tools/extract_dialog_roles.py
"""

from __future__ import annotations

import os
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dialog_roles import classify_bbp, role_of  # noqa: E402

GAME = r"C:\Program Files (x86)\Steam\steamapps\common\Warhammer 40,000 Rogue Trader"
BBP = os.path.join(GAME, "Bundles", "blueprints-pack.bbp")
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "catalog" / "dialog_roles.yaml"


def main() -> int:
    if not os.path.exists(BBP):
        print(f"ERROR: {BBP} not found")
        return 1

    t0 = time.time()
    with open(BBP, "rb") as f:
        data = f.read()
    print(f"BBP: {len(data) / 1024 / 1024:.0f}MB, scanning...")

    roles = classify_bbp(data)
    result = {}
    counts = Counter()
    for guid, role_set in roles.items():
        role = role_of(roles, guid)
        result[guid] = role
        counts[role] += 1

    print(f"Classified: {len(result)} GUIDs in {time.time() - t0:.0f}s")
    print(f"  answer: {counts['answer']}")
    print(f"  cue:    {counts['cue']}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(f"# Generated by tools/extract_dialog_roles.py\n")
        f.write(f"# Roles: answer (player option) | cue (NPC line). Missing GUIDs = unknown.\n")
        for guid in sorted(result):
            f.write(f"{guid}: {result[guid]}\n")
    print(f"Saved to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
